version: '3.9'
services: 
  admin_api:
    container_name: django_api
    build: 
      context: .
      dockerfile: Dockerfile

    volumes: 
      - .:/app

    ports: 
      - 8000:8000

    depends_on: 
      - admin_db
  
  admin_db:
    container_name: django_admin_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_DATABASE: django_admin
      MYSQL_USER: vinod
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306